version: '2'

services:
    fhem:
        restart: always
        ports:
            - "8083:8083"
            - "7072:7072"
        image: fhem/fhem:latest
        volumes:
            - /data/docker/fhem-docker/fhem/core/:/opt/fhem/
        networks:
            - fhem-network
        environment:
            FHEM_UID: 1000
            FHEM_GID: 999
            TIMEOUT: 10
            RESTART: 1
            TELNETPORT: 7072
            TZ: Europe/Berlin
        depends_on:
            - "mysql"
            - "mqtt"

    habridge:
        restart: always
        build: habridge
        network_mode: host
        volumes:
            - /data/docker/fhem-docker/habridge/data/:/opt/habridge/data/

    mysql:
        restart: always
        expose:
            - "3306"
            - "33060"
        ports:
            - "3306:3306"
            - "33060:33060"
        image: mysql/mysql-server:5.7
        volumes:
            - /data/docker/fhem-docker/mysql/init.sql:/docker-entrypoint-initdb.d/fhem-init.sql
            - /data/docker/fhem-docker/mysql/data:/var/lib/mysql
        environment:
            - MYSQL_RANDOM_ROOT_PASSWORD=yes
        networks:
            - fhem-network

    mqtt:
        restart: always
        expose:
            - "1883"
            - "9001"
        ports:
            - "1883:1883"
            - "9001:9001"
        image: toke/mosquitto
        networks:
            - fhem-network
        volumes:
            - /data/docker/fhem-docker/mqtt/config/:/mqtt/config/
            - /data/docker/fhem-docker/mqtt/log/:/mqtt/log/
            - /data/docker/fhem-docker/mqtt/data/:/mqtt/data/

    nodered:
        restart: always
        expose:
            - "1880"
        ports:
            - "1880:1880"
        image: nodered/node-red-docker:latest
        user: "1000:999"
        volumes:
            - /data/docker/fhem-docker/nodered/data/:/data/
        networks:
            - fhem-network
        depends_on:
            - "mqtt"

networks:
    fhem-network:
        driver: bridge
